### ISSUE TITLE
Update build script to publish to real NPM.

### ISSUE THREAD

**Issue by Alendri** [allbin/allbin-bar#6]
Blocked until further discussions about allbin-bars future are completed. Discussions scheduled for 2021-03-25.

**Comment by mdjarv** [comment]
# AllbinBar

## Features

- Contact us / About
- Changelog
- Dashboard
- Help
- User information
- Language picker
- Logout

## Suggestions

- Make separate "profile-hooks" package with no UI

### Changelog

Present CHANGELOG.md in UI, react-markdown could be used, ticket already exists

### Contact us / About

Email to support and possibly a phone number is enough

### Dashboard link

-

### Help

Project specific
